name: Generate Datas
on:
  schedule:
    - cron: "0 */12 * * *"  # a cada 12 horas, no minuto zero
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: chiquinelli-bia
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update github contribution snake images"
          branch: output
          file_pattern: dist/*
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com
